### PR TITLE
adds gendered addons, fixes north/south headoffset

### PR DESCRIPTION
**Pull request by FoggyMorning**
I wanted to have body addons that only work for one gender, like a deer's antlers.  So this pull request adds the drawForMale and drawForFemale variables.   Also I found that the headoffset patch was applying the x axis offset to the north and south images when it should only apply to the east and west images, so I applied a fix for that as well.

### CODE REVIEW

**Comment by erdelf** [comment]
I disagree on the head offset, otherwise nice pr.
If you remove that, I'll accept.

**Comment by FoggyMorning** [comment]
Thanks @erdelf.  Could you give me a reason you don't agree with the head offset change? 

The switch I used is functionally equivalent to the switch used by verse.BaseHeadOffsetAt.  If you are worried that some dependent mods will break with this fix, then I can add an additional var to allow the north/south x movement to be disabled.  I would consider other options as well, I would just like this to behave the same as the base game.

**Comment by erdelf** [comment]
Well for one that.
But mostly, the very cases that asked for this feature required x offset.

**Comment by FoggyMorning** [comment]
Alright, I've removed the head offset changes.  I'm going to try and build a patch mod for the head offset stuff.  Should be an interesting learning experience.

**Comment by erdelf** [comment]
Thank you. Consider this pr merged. I'll merge it with the next update that should be coming soon.

**Pull request merged**
